### ISSUE TITLE
Handling of "itertools"?

### ISSUE THREAD

**Issue by epage** [AndWass/pushgen#27]
I've re-implemented the minimum of `itertools::Either` with `Generator`.  Is that and other `itertools` wanted upstream?  If so, any preference for how to handle it?

**Comment by AndWass** [comment]
My plan was to eventually also support itertools as well so any help is much appreciated. For now I think they can live in `GemeratorExt` as well. If it becomes too unwieldy it can always be split later.

I am very curious of your results when you have them!

**Comment by epage** [comment]
Thanks!
