### ISSUE TITLE
Support for Boxed Generators

### ISSUE THREAD

**Issue by epage** [AndWass/pushgen#35]
I think the `impl` argument for run makes it so `Generator` is not object-safe and therefore can't be boxed
```
fn run(&mut self, output: impl FnMut(Self::Output) -> crate::ValueResult) -> GeneratorResult;
```

While in most cases, boxing isn't needed, for a trait to return a `Generator`, it needs to be boxed to allow the trait impls to create whatever `Generator` they need.

**Comment by AndWass** [comment]
Hmm tricky one! 

I have an idea that involves adding another `DynGenerator` trait which is object safe with blanket implementation for `Generator`. Shouldn't you then be able to box a `dyn DynGenerator`? I'll do some testing!

**Comment by AndWass** [comment]
What do you think of the approach taken in #37?

**Comment by epage** [comment]
Looks good to me
